        - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Upgrading to the recommended Node 22 for Hardhat 3

      - name: Compile Smart Contracts
        # The '--config' flag stops Hardhat from 'guessing' where the file is
        run: npx hardhat compile --config hardhat.config.cjs
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
